import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import LayoutWrapperReduxStore from "./LayoutWrapperReduxStoreProvider";
import LayoutWrapper from "./LayoutWrapper";

export const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"]
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
        <LayoutWrapperReduxStore>
          <LayoutWrapper>{children}</LayoutWrapper>
        </LayoutWrapperReduxStore>
      </body>
    </html>
  );
}